apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: web
        image: amisha4002/flask-ecommerce:latest   # replace with your image
        ports:
        - containerPort: 5000
        env:
        # First define all the component variables
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: database_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: database_password
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: database_host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: database_port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: database_name
        # Now DATABASE_URL can use those variables
        - name: DATABASE_URL
          value: "mysql+pymysql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
        # Finally, SECRET_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret
              key: secret_key
        