apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort   # or LoadBalancer if on cloud; for minikube we use NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000   # optional, range 30000-32767
  selector:
    app: ecommerce-backend