apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  database_name: flask_ecommerce
  database_user: ecommerce_user
  database_host: mysql-service   # name of the MySQL service
  database_port: "3306"